#!/bin/bash
set -x

sudo -i systemctl stop namenode
sudo -i systemctl stop datanode
hdfs namenode -format
sudo -i rm -fr /mnt/nvme_ssd0/hops/hopsdata/hdfs/dn/cloud/*
sudo -i rm -fr /mnt/nvme_ssd0/hops/hopsdata/hdfs/dn/disk/*
sudo -i rm /mnt/nvme_ssd0/hops/hadoop/logs/*
sudo -i systemctl start namenode
sudo -i systemctl start datanode
./set-hdfs-storage-policy.sh / CLOUD
